# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.1-node-browsers

         environment:
          - RAILS_ENV: test
          - DATABASE_URL: postgres://postgres:postgres@localhost:5432
       - image: circleci/postgres
         environment:
           - POSTGRES_USER: postgres
           - POSTGRES_PASSWORD: postgres
           - POSTGRES_DB: spotibox_test

    working_directory: ~/spotibox
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: bundle exec rake db:create db:schema:load

      # run tests!
      - run:
          name: Run Tests
          command: |
            bundle exec rspec
      # run the linters
      - run:
          name: Rubocop
          command: |
            bundle exec rubocop --require rubocop-rspec
      # run static code analysis
      - run:
          name: Brakeman
          command: |
            mkdir /tmp/brakeman-results
            (bundle exec brakeman || true) > /tmp/brakeman-results/brakeman-report.txt
      # check for outdated gems
      - run:
          name: Bundle Audit
          command: |
            mkdir /tmp/bundle-audit-results
            (bundle exec bundle-audit || true) > /tmp/bundle-audit-results/bundle-report.txt
      # store artifacts
      - store_artifacts:
          path: /tmp/brakeman-results
          destination: brakeman-results
      - store_artifacts:
          path: /tmp/bundle-audit-results
          destination: bundle-audit-results
